apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# renovate: datasource=git-refs depName=https://github.com/dalibo/cnpg-plugin-pgbackrest
- https://github.com/dalibo/cnpg-plugin-pgbackrest//config/crd/bases?ref=4386147f2109f9927d216b9fe19cb29ba568e5ef
