repository: https://grafana.github.io/helm-charts
chart: loki
version: 6.24.0
values:
  loki:
    useTestSchema: true
    storage:
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      type: s3
      s3:
        endpoint: http://minio:9000
        region: us-east-1
        secretAccessKey: supersecret
        accessKeyId: minioaccess
        s3ForcePathStyle: true
        insecure: true
